name: Update EPG

on:
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir çalışır (UTC)
  workflow_dispatch:       # Manuel olarak da tetikleyebilirsin

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: EPG dosyasını indir
        run: |
          curl -L "https://www.open-epg.com/generate/lQn8VptSXU.xml" -o epg.xml

      - name: Git commit ve push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add epg.xml
          git commit -m "Auto update EPG $(date)" || echo "No changes"
          git push
