name: Merge Multiple EPGs

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download and merge EPG files
        run: |
          curl -L "https://www.open-epg.com/generate/lQn8VptSXU.xml" -o epg1.xml
          curl -L "https://androbjk34.serv00.net/epg.php" -o epg2.xml
          echo "<tv>" > epg.xml
          grep -h "<programme" epg1.xml >> epg.xml
          grep -h "<programme" epg2.xml >> epg.xml
          echo "</tv>" >> epg.xml

      - name: Commit merged file
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add epg.xml
          git commit -m "Merged EPG update $(date)" || echo "No changes"
          git push
